name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.5.0
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm test
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.2
        with:
          exclusions: '*.git* /* .stack.yaml'
